# Generated by Django 2.0.7 on 2018-07-26 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('random_number', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
